service: serverless-aws-lambda-receiver-bolt-js
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    SLACK_SIGNING_SECRET:  ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    MONGO_URL: ${env:MONGO_URL}
    ADMINS: ${env:ADMINS}
    HR1: ${env:HR1}
    HR2: ${env:HR2}
    HR3: ${env:HR3}
    CHANNEL_GENERAL_ID: ${env:CHANNEL_GENERAL_ID}
functions:
  authorization:
    handler: src/api.authorization
    events:
       - http:
            path: slack/oauth
            method: get
  slack:
    handler: src/api.handler
    events:
      - http:
          path: slack/events
          method: post
  cronHandler:
    handler: src/api.cronJob
    events:
      - schedule: cron(0 0 1 1/1 ? *)
useDotenv: true
plugins:
  - serverless-offline
